name: Visual Studio

on:
  workflow_dispatch:
  pull_request:
    branches: [m4a]
    paths-ignore:
      - "**/*.md"
      - "**/*.json"
      - "docs/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake (x64)
        run: cmake --preset vs-x64

      - name: Build (x64)
        run: cmake --build --preset vs-x64-release --verbose

      # - name: Configure CMake (x86)
      #   run: cmake --preset vs-x86

      # - name: Build (x86)
      #   run: cmake --build --preset vs-x86-release --verbose
